services:
  django:
    build:
      context:  ./app/backend/
      dockerfile: Dockerfile
    container_name: mau_schedule_backend
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - PYTHONPATH=/usr/src/app
      - PYTHONUTF8=1
      - POSTGRES_HOST=postgres_db
      - REDIS_HOST=redis
    command: >
      bash -c
      "django-admin makemigrations
      && django-admin migrate
      && django-admin runserver_plus 0.0.0.0:8000 --cert-file /usr/src/secrets/localhost.crt --key-file /usr/src/secrets/localhost.key"
    ports:
      - "8000:8000"
    volumes:
      - ./secrets:/usr/src/secrets
      - ./app/backend/app:/usr/src/app
    depends_on:
      - postgres_db
      - redis

  react:
    build:
      context: ./app/frontend/
      dockerfile: Dockerfile
    container_name: mau_schedule_frontend
    env_file:
      - .env
    environment:
      - HTTPS=true
      - SSL_CRT_FILE=/usr/app/secrets/localhost.crt
      - SSL_KEY_FILE=/usr/app/secrets/localhost.key
      - WATCHPACK_POLLING=true
    command: >
      bash -c
      "npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./secrets:/usr/app/secrets
      - ./app/frontend/src:/usr/app/src
      - ./app/frontend/public:/usr/app/public
    depends_on:
      - django

  postgres_db:
    image: postgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5000:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./app/backend/
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=postgres_db
      - REDIS_HOST=redis
    command: celery -A app worker -l info
    volumes:
      - celery_data:/usr/src/app/
    depends_on:
      - redis

  celery-beat:
    build:
      context: ./app/backend/
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=postgres_db
      - REDIS_HOST=redis
    command: celery -A app beat -l info
    volumes:
      - celery_data:/usr/src/app/
    depends_on:
      - redis

volumes:
  db_data:
  celery_data:
