version: '3'

services:
  app:
    build: .
    container_name: mau_schedule
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - PYTHONPATH=/usr/src/app
      - PYTHONUTF8=1
      - POSTGRES_HOST=postgres_db
      - REDIS_HOST=redis
    command: >
      bash -c
      "django-admin makemigrations
      && django-admin migrate
      && django-admin runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - postgres_db
      - redis

  postgres_db:
    image: postgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5000:5432'

  redis:
    image: redis
    ports:
      - '6379:6379'

  celery:
    build: .
    env_file:
      - .env
    environment:
      - DB_HOST=postgres_db
      - REDIS_HOST=redis
    command: celery -A app worker -l info
    volumes:
      - celery_data:/usr/src/app/
    depends_on:
      - redis

  celery-beat:
    build: .
    env_file:
      - .env
    environment:
      - DB_HOST=postgres_db
      - REDIS_HOST=redis
    command: celery -A app beat -l info
    volumes:
      - celery_data:/usr/src/app/
    depends_on:
      - redis

volumes:
  db_data:
  celery_data:
