version: '3'

services:
  app:
    build:
      dockerfile: ./Dockerfile.prod
    container_name: mau_schedule
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - PYTHONPATH=/usr/src/app
      - PYTHONUTF8=1
      - DB_HOST=postgres_db
      - REDIS_HOST=redis
    command: >
      bash -c
      "django-admin makemigrations
      && django-admin migrate
      && django-admin collectstatic --no-input
      && gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_data:/usr/src/app/staticfiles
    expose:
      - 8000
    depends_on:
      - postgres_db

  nginx:
    build: ./nginx
    ports:
      - '1337:80'
    volumes:
      - static_data:/home/app/staticfiles
    depends_on:
      - app

  postgres_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12321
      - POSTGRES_USER=mau_admin
      - POSTGRES_DB=mau_schedule
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5000:5432'

  redis:
    image: redis
    ports:
      - '6379:6379'

  celery:
    build:
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    environment:
      - DB_HOST=postgres_db
      - REDIS_HOST=redis
    command: celery -A app worker -l info
    volumes:
      - celery_data:/usr/src/app/
    depends_on:
      - redis

  celery-beat:
    build:
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    environment:
      - DB_HOST=postgres_db
      - REDIS_HOST=redis
    command: celery -A app beat -l info
    volumes:
      - celery_data:/usr/src/app/
    depends_on:
      - redis

volumes:
  static_data:
  db_data:
  celery_data:
