version: '3'

services:
  app:
    build: .
    container_name: mau_schedule
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - PYTHONPATH=/usr/src/app
    command: ['django-admin', 'runserver', '0.0.0.0:8000']
    ports:
      - '8080:8000'
    depends_on:
      - postgres_db
    volumes:
      - ./requirements:/requirements

  postgres_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12321
      - POSTGRES_USER=mau_admin
      - POSTGRES_DB=mau_schedule
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db_data:
