# Generated by Django 5.1.4 on 2024-12-17 21:24

import django.db.models.deletion
import mau_auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mau_auth", "0001_initial"),
        ("schedule", "0002_auto_20241211_1957"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mauuser",
            options={
                "ordering": ("course", "full_name"),
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AlterField(
            model_name="mauuser",
            name="course",
            field=models.PositiveSmallIntegerField(null=True, verbose_name="course"),
        ),
        migrations.AlterField(
            model_name="mauuser",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[mau_auth.validators.validate_email],
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="mauuser",
            name="full_name",
            field=models.CharField(
                max_length=50,
                validators=[mau_auth.validators.validate_full_name],
                verbose_name="full name",
            ),
        ),
        migrations.AlterField(
            model_name="mauuser",
            name="group",
            field=models.CharField(max_length=20, null=True, verbose_name="group"),
        ),
        migrations.AlterField(
            model_name="mauuser",
            name="institute",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mauusers",
                to="schedule.mauinstitute",
                verbose_name="institute",
            ),
        ),
    ]
