# Generated by Django 5.0.2 on 2024-03-09 14:26

from django.db import migrations
from django.conf import settings

from mau_auth.models import MauInstitute


def set_institutes(apps, schema_editor):
    for institute_name in settings.INSTITUTES:
        MauInstitute.objects.get_or_create(name=institute_name)


class Migration(migrations.Migration):

    dependencies = [
        ("mau_auth", "0003_maugroup_mauinstitute_alter_mauuser_options_and_more"),
    ]

    operations = [
        migrations.RunPython(set_institutes),
    ]
