# Generated by Django 5.1.4 on 2024-12-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="group",
            field=models.CharField(verbose_name="group"),
        ),
    ]
