# Generated by Django 5.1.4 on 2025-05-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_alter_note_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="group",
        ),
        migrations.AddField(
            model_name="note",
            name="schedule_key",
            field=models.CharField(null=True, verbose_name="schedule key"),
        ),
    ]
