# Generated by Django 5.2.1 on 2025-05-14 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_group_note_schedule_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('user', 'schedule_name', 'schedule_key', 'day', 'lesson_number'), name='unique_note'),
        ),
    ]
