# Generated by Django 5.0.2 on 2024-04-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='schedule_name',
            field=models.CharField(null=True, verbose_name='название таблицы'),
        ),
    ]
