# Generated by Django 5.0.2 on 2024-04-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_note_schedule_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="group",
            field=models.CharField(null=True, verbose_name="группа"),
        ),
    ]
