# Generated by Django 5.0.2 on 2024-04-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_note_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="expired_date",
            field=models.DateField(null=True, verbose_name="Дата удаления"),
        ),
    ]
