# Generated by Django 5.1.1 on 2024-09-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_remove_note_day_remove_note_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="location",
            field=models.CharField(null=True, verbose_name="расположение"),
        ),
    ]
