# Generated by Django 5.1.1 on 2024-12-11 16:57

from django.db import migrations
from django.conf import settings

from schedule.models import MauInstitute


def set_institutes(apps, schema_editor):
    for institute_name in settings.INSTITUTES:
        MauInstitute.objects.get_or_create(name=institute_name)


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(set_institutes),
    ]
